project: 
  type: website

website:
  title: "Ketsiammen Peter - Data Science Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/username/username.github.io
  #repo-actions: [issue] # Uncomment if needed

page-footer:
  border: true
  left: "ketsiammen_Peter 2024©"
  right:
    - icon: fab fa-linkedin  # Font Awesome icon for LinkedIn
      href: "https://www.linkedin.com/in/ketsiammen-monthe-yann-peter-b690ab263"

navbar:
  background: primary  # Assuming 'primary' is defined in your theme
  search: true
  right:
    - text: "Home"
      file: index.qmd
    - text: "My Resume"
      file: resume.qmd
    - text: "Data Cleansing"
      file: cleansing.qmd
      icon: fas fa-tint  # Font Awesome icon for data cleansing
    - text: "Data Exploration"
      file: exploration.qmd
      icon: fas fa-chart-line  # Font Awesome icon for data exploration
    - text: "Story Telling"
      file: story_telling.qmd
      icon: fas fa-book-open  # Font Awesome icon for storytelling
    - text: "Machine Learning"
      file: ml.qmd
      icon: fas fa-code  # Font Awesome icon for machine learning
    - text: "Full Stack"
      file: full_stack.qmd
      icon: fas fa-layer-group  # Font Awesome icon for full stack
    - text: "Competition"
      file: competition.qmd
      icon: fas fa-trophy  # Font Awesome icon for competition

sidebar: 
  - title: "Data Cleansing"
    style: "docked"
    background: light
    contents:
      - text: "Data Cleansing"
        file: cleansing.qmd
      - text: "---"
      - text: "Project 1"
        file: Cleansing_Projects/project1.qmd
      - text: "---"
      - text: "Project 2"
        file: Cleansing_Projects/project2.qmd
      - text: "---"
      - text: "Project 3"
        file: Cleansing_Projects/project3.qmd
      - text: "---"
      - text: "Project 4"
        file: Cleansing_Projects/project4.qmd
      - text: "---"
      - text: "Project 5"
        file: Cleansing_Projects/project5.qmd
      - text: "---"
  - title: "Data Exploration"
    style: "docked"
    background: light
    contents:
      - text: "Data Exploration"
        file: exploration.qmd
      - text: "---"
      - text: "Project 1"
        file: Exploration_Projects/project1.qmd
      - text: "---"
      - text: "Project 2"
        file: Exploration_Projects/project2.qmd
      - text: "---"
      - text: "Project 3"
        file: Exploration_Projects/project3.qmd
      - text: "---"
      - text: "Project 4"
        file: Exploration_Projects/project4.qmd
      - text: "---"
      - text: "Project 5"
        file: Exploration_Projects/project5.qmd
      - text: "---"
  - title: "Story Telling"
    style: "docked"
    background: light
    contents:
      - text: "Story Telling"
        file: story_telling.qmd
      - text: "---"
      - text: "Project 1"
        file: Story_Telling/project1.qmd
      - text: "---"
      - text: "Project 2"
        file: Story_Telling/project2.qmd
      - text: "---"
      - text: "Project 3"
        file: Story_Telling/project3.qmd
      - text: "---"
      - text: "Project 4"
        file: Story_Telling/project4.qmd
      - text: "---"
      - text: "Project 5"
        file: Story_Telling/project5.qmd
      - text: "---"
  - title: "Machine Learning"
    style: "docked"
    background: light
    contents:
      - text: "Machine Learning"
        file: ml.qmd
      - text: "---"
      - text: "Project 1"
        file: Machine_Learning/project1.qmd
      - text: "---"
      - text: "Project 2"
        file: Machine_Learning/project2.qmd
      - text: "---"
      - text: "Project 3"
        file: Machine_Learning/project3.qmd
      - text: "---"
      - text: "Project 4"
        file: Machine_Learning/project4.qmd
      - text: "---"
      - text: "Project 5"
        file: Machine_Learning/project5.qmd
      - text: "---"
  - title: "Full Stack"
    style: "docked"
    background: light
    contents:
      - text: "Full Stack"
        file: full_stack.qmd
      - text: "---"
      - text: "Project 1"
        file: Full_Stack/project1.qmd
      - text: "---"
      - text: "Project 2"
        file: Full_Stack/project2.qmd
      - text: "---"
      - text: "Project 3"
        file: Full_Stack/project3.qmd
      - text: "---"
      - text: "Project 4"
        file: Full_Stack/project4.qmd
      - text: "---"
      - text: "Project 5"
        file: Full_Stack/project5.qmd
      - text: "---"
  - title: "Competition"
    style: "docked"
    background: light
    contents:
      - text: "Competition"
        file: competition.qmd
      - text: "---"
      - text: "Project 1"
        file: Competition/project1.qmd
      - text: "---"
      - text: "Project 2"
        file: Competition/project2.qmd
      - text: "---"
      - text: "Project 3"
        file: Competition/project3.qmd
      - text: "---"
      - text: "Project 4"
        file: Competition/project4.qmd
      - text: "---"
      - text: "Project 5"
        file: Competition/project5.qmd
      - text: "---"

format:
  html:
    theme: flatly  # Or your chosen theme from Quarto
    dark: darkly
    css: styles.css  # Include your custom CSS file for further styling
   toc: true
